// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ApplicationResourcesSortKey application resources sort key
//
// swagger:model ApplicationResourcesSortKey
type ApplicationResourcesSortKey string

func NewApplicationResourcesSortKey(value ApplicationResourcesSortKey) *ApplicationResourcesSortKey {
	v := value
	return &v
}

const (

	// ApplicationResourcesSortKeyResourceName captures enum value "resourceName"
	ApplicationResourcesSortKeyResourceName ApplicationResourcesSortKey = "resourceName"

	// ApplicationResourcesSortKeyResourceHash captures enum value "resourceHash"
	ApplicationResourcesSortKeyResourceHash ApplicationResourcesSortKey = "resourceHash"

	// ApplicationResourcesSortKeyResourceType captures enum value "resourceType"
	ApplicationResourcesSortKeyResourceType ApplicationResourcesSortKey = "resourceType"

	// ApplicationResourcesSortKeyVulnerabilities captures enum value "vulnerabilities"
	ApplicationResourcesSortKeyVulnerabilities ApplicationResourcesSortKey = "vulnerabilities"

	// ApplicationResourcesSortKeyApplications captures enum value "applications"
	ApplicationResourcesSortKeyApplications ApplicationResourcesSortKey = "applications"

	// ApplicationResourcesSortKeyPackages captures enum value "packages"
	ApplicationResourcesSortKeyPackages ApplicationResourcesSortKey = "packages"
)

// for schema
var applicationResourcesSortKeyEnum []interface{}

func init() {
	var res []ApplicationResourcesSortKey
	if err := json.Unmarshal([]byte(`["resourceName","resourceHash","resourceType","vulnerabilities","applications","packages"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		applicationResourcesSortKeyEnum = append(applicationResourcesSortKeyEnum, v)
	}
}

func (m ApplicationResourcesSortKey) validateApplicationResourcesSortKeyEnum(path, location string, value ApplicationResourcesSortKey) error {
	if err := validate.EnumCase(path, location, value, applicationResourcesSortKeyEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this application resources sort key
func (m ApplicationResourcesSortKey) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateApplicationResourcesSortKeyEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this application resources sort key based on context it is used
func (m ApplicationResourcesSortKey) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
