// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RuntimeQuickScanConfig Runtime quick scan configuration
//
// swagger:model RuntimeQuickScanConfig
type RuntimeQuickScanConfig struct {

	// cis docker benchmark scan enabled
	CisDockerBenchmarkScanEnabled bool `json:"cisDockerBenchmarkScanEnabled,omitempty"`
}

// Validate validates this runtime quick scan config
func (m *RuntimeQuickScanConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this runtime quick scan config based on context it is used
func (m *RuntimeQuickScanConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RuntimeQuickScanConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RuntimeQuickScanConfig) UnmarshalBinary(b []byte) error {
	var res RuntimeQuickScanConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
