run:
  timeout: 20m

linters-settings:
  golint:
    min-confidence: 0.1
  goimports:
    local-prefixes: github.com/openclarity/vmclarity
  errorlint:
    # Check whether fmt.Errorf uses the %w verb for formatting errors. See the readme for caveats
    errorf: true
  gomoddirectives:
    # Allow local `replace` directives. Default is false.
    replace-local: true
    # List of allowed `replace` directives. Default is empty.
    replace-allow-list:
      # github.com/openclarity/kubeclarity job-manager-changes
      - github.com/openclarity/kubeclarity/api
      - github.com/openclarity/kubeclarity/cli
      - github.com/openclarity/kubeclarity/shared
      # Replace these for trivy
      - github.com/docker/docker
      - oras.land/oras-go
      # End-to-end testing
      - cloud.google.com/go
      - go.opentelemetry.io/otel
      - go.opentelemetry.io/otel/metric
      - go.opentelemetry.io/otel/sdk
      # Viper
      - github.com/mitchellh/mapstructure

  gosec:
    # To specify a set of rules to explicitly exclude.
    # Available rules: https://github.com/securego/gosec#available-rules
#    excludes:
#      - G404 # Insecure random number source (rand)
  forbidigo:
    # Forbid the following identifiers (identifiers are written using regexp):
    forbid:
      - ^print.*$

  cyclop:
    max-complexity: 15

linters:
  enable-all: true
  disable:
    - musttag
    - revive
    - maligned
    - funlen
    - dupl
    - nestif
    - wsl
    - lll
    - interfacer
    - exhaustivestruct
    - nlreturn
    - gocritic
    - gochecknoglobals
    - testpackage
    - goerr113
    - paralleltest
    - godox # Allow TODOs
    - tagliatelle # Allow json(camel)
    - scopelint # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - deadcode # deprecated
    - varcheck # deprecated
    - structcheck # deprecated
    - nosnakecase # deprecated
    - gochecknoinits # Allow init function
    - nolintlint # Allow nolint
    - varnamelen # Allow short var names
    - ireturn # Allow returning with interfaces
    - exhaustruct # Allow structures with uninitialized fields
    - gci # imports still has gci lint errors after run `gci write --skip-generated -s standard -s default -s "prefix(github.com/openclarity/vmclarity)"`
    - depguard # NOTE(chrisgacsal): need discussion before enabling it
    - tagalign # NOTE(chrisgacsal): does not seem to provide much value

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - govet
    - path: pkg/apiserver/database/demo.go
      linters:
        - gomnd
