# syntax=docker/dockerfile:1.2
FROM --platform=$BUILDPLATFORM node:20-slim AS site-build

WORKDIR /app/ui-build

COPY ui .
RUN npm i
RUN npm run build

FROM nginx:1.25.2

COPY --from=site-build ["/app/ui-build/nginx.conf", "/etc/nginx/conf.d/default.conf"]

COPY --from=site-build ["/app/ui-build/build", "/usr/share/nginx/html"]
