# syntax=docker/dockerfile:1

FROM --platform=$BUILDPLATFORM node:20-slim AS site-build

WORKDIR /src

COPY --link ./ui /src

RUN --mount=type=cache,target=/src/node_modules \
    npm install

RUN --mount=type=cache,target=/src/node_modules \
    npm run build

FROM nginx:1.25.3

COPY --from=site-build ["/src/build", "/usr/share/nginx/html"]

COPY --link ["ui/nginx.conf", "/etc/nginx/conf.d/default.conf"]
