# syntax=docker/dockerfile:1@sha256:dbbd5e059e8a07ff7ea6233b213b36aa516b4c53c645f1817a4dd18b83cbea56

FROM --platform=$BUILDPLATFORM node:20-slim AS site-build

WORKDIR /src

COPY --link ./ui /src

RUN --mount=type=cache,target=/src/node_modules \
    npm install

RUN --mount=type=cache,target=/src/node_modules \
    npm run build

FROM nginx:1.25.4@sha256:9ff236ed47fe39cf1f0acf349d0e5137f8b8a6fd0b46e5117a401010e56222e1

COPY --from=site-build ["/src/build", "/usr/share/nginx/html"]

COPY --link ["ui/nginx.conf", "/etc/nginx/conf.d/default.conf"]
