{{- if eq .Values.orchestrator.provider "kubernetes" -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "openclarity.crDiscoveryServer.name" . }}
  labels: {{- include "openclarity.crDiscoveryServer.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "openclarity.crDiscoveryServer.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "openclarity.crDiscoveryServer.labels.standard" . | nindent 8 }}
    spec:
      {{- if .Values.crDiscoveryServer.affinity }}
      affinity: {{- .Values.crDiscoveryServer.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.crDiscoveryServer.nodeSelector }}
      nodeSelector: {{- .Values.crDiscoveryServer.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.crDiscoveryServer.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.crDiscoveryServer.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.crDiscoveryServer.tolerations }}
      tolerations: {{- .Values.crDiscoveryServer.tolerations | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: cr-discovery-server
          image: {{ include "openclarity.images.image" ( dict "imageRoot" .Values.crDiscoveryServer.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.crDiscoveryServer.image.pullPolicy | quote }}
          {{- if .Values.crDiscoveryServer.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.crDiscoveryServer.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.crDiscoveryServer.resources }}
          resources: {{- toYaml .Values.crDiscoveryServer.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.crDiscoveryServer.env }}
          env: {{- toYaml .Values.crDiscoveryServer.env | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- range .Values.crDiscoveryServer.containerRuntimePaths }}
            - name: {{ .name }}
              mountPath: {{ .path }}
              {{- if .readOnly }}
              readOnly: true
              {{- end }}
            {{- end }}
      volumes:
        {{- range .Values.crDiscoveryServer.containerRuntimePaths }}
        - name: {{ .name }}
          hostPath:
            path: {{ .path }}
        {{- end }}
      serviceAccountName: {{ include "openclarity.crDiscoveryServer.serviceAccountName" . }}
{{- end -}}
