{
 "title": "KubeClarity",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(kubeclarity_application_vulnerability, environment)"
    }
   },
   {
    "name": "severity",
    "query": {
     "query": "label_values(kubeclarity_application_vulnerability, severity)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Vulnerabilities by environment and severity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Application vulnerabilities in $environment",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (severity) (kubeclarity_application_vulnerability{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Environments with vulnerabilities at $severity level",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (environment) (kubeclarity_application_vulnerability{severity=\"$severity\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application vulnerabilities of level $severity in $environment",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (kubeclarity_application_vulnerability{environment=\"$environment\", severity=\"$severity\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview of vulnerabilities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Trend at $severity level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (environment) (kubeclarity_application_vulnerability{severity=\"$severity\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of packages / libraries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubeclarity_number_of_packages)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Types of vulnerabilities",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubeclarity_number_of_fixable_vulnerabilities_amount)",
     "legendFormat": "Fixable vulnerabilities"
    },
    {
     "expr": "sum(kubeclarity_number_of_vulnerabilities_amount)-sum(kubeclarity_number_of_fixable_vulnerabilities_amount)",
     "legendFormat": "Vulnerabilities without fix"
    }
   ]
  },
  {
   "title": "Number of resources",
   "type": "stat",
   "description": "This is image, directory or file, typically image",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubeclarity_number_of_resources)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fixable  vulnerabilities vs no known fix",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(kubeclarity_number_of_fixable_vulnerabilities_amount)",
     "legendFormat": "Fixable vulnerabilities"
    },
    {
     "expr": "sum(kubeclarity_number_of_vulnerabilities_amount)  ",
     "legendFormat": "Vulnerabilities with no known fix"
    }
   ]
  },
  {
   "title": "Vulnerabilities by severity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "sum by (severity) (kubeclarity_number_of_vulnerabilities)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fixable vulnerabilities by severity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 18 },
   "targets": [
    {
     "expr": "sum by (severity) (kubeclarity_number_of_fixable_vulnerabilities)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}