export const ICON_NAMES = {
    DASHBOARD: "dashboard",
    APPLICATION: "application",
    RESOURCE: "resource",
    PACKAGE: "package",
    VULNERABILITY: "vulnerability",
    BUG: "bug",
    SCAN: "scan",
    X_MARK: "x-mark",
    CHECK_MARK: "check-mark",
    STROKE: "stroke",
    SORT: "sort",
    CHEVRON_RIGHT: "chevron-right",
    CHEVRON_RIGHT_DOUBLE: "chevron-right-double",
    ARROW_LEFT: "arrow-left",
    REFRESH: "refresh",
    FILTER: "filter",
    ALERT: "alert",
    BANDAID: "bandaid",
    START_TIME: "start-time",
    END_TIME: "end-time",
    PLUS: "plus",
    DELETE: "delete",
    EDIT: "edit",
    INFO: "info",
    COG: "cog",
    CLOCK: "clock"
}