// Code generated by go-swagger; DO NOT EDIT.

package component

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openclarity/kubeclarity/shared/pkg/scanner/dependency_track/api/client/models"
)

// GetComponentByUUIDReader is a Reader for the GetComponentByUUID structure.
type GetComponentByUUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetComponentByUUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetComponentByUUIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetComponentByUUIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetComponentByUUIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetComponentByUUIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetComponentByUUIDOK creates a GetComponentByUUIDOK with default headers values
func NewGetComponentByUUIDOK() *GetComponentByUUIDOK {
	return &GetComponentByUUIDOK{}
}

/* GetComponentByUUIDOK describes a response with status code 200, with default header values.

successful operation
*/
type GetComponentByUUIDOK struct {
	Payload *models.Component
}

func (o *GetComponentByUUIDOK) Error() string {
	return fmt.Sprintf("[GET /v1/component/{uuid}][%d] getComponentByUuidOK  %+v", 200, o.Payload)
}
func (o *GetComponentByUUIDOK) GetPayload() *models.Component {
	return o.Payload
}

func (o *GetComponentByUUIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Component)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetComponentByUUIDUnauthorized creates a GetComponentByUUIDUnauthorized with default headers values
func NewGetComponentByUUIDUnauthorized() *GetComponentByUUIDUnauthorized {
	return &GetComponentByUUIDUnauthorized{}
}

/* GetComponentByUUIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetComponentByUUIDUnauthorized struct {
}

func (o *GetComponentByUUIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/component/{uuid}][%d] getComponentByUuidUnauthorized ", 401)
}

func (o *GetComponentByUUIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetComponentByUUIDForbidden creates a GetComponentByUUIDForbidden with default headers values
func NewGetComponentByUUIDForbidden() *GetComponentByUUIDForbidden {
	return &GetComponentByUUIDForbidden{}
}

/* GetComponentByUUIDForbidden describes a response with status code 403, with default header values.

Access to the specified component is forbidden
*/
type GetComponentByUUIDForbidden struct {
}

func (o *GetComponentByUUIDForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/component/{uuid}][%d] getComponentByUuidForbidden ", 403)
}

func (o *GetComponentByUUIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetComponentByUUIDNotFound creates a GetComponentByUUIDNotFound with default headers values
func NewGetComponentByUUIDNotFound() *GetComponentByUUIDNotFound {
	return &GetComponentByUUIDNotFound{}
}

/* GetComponentByUUIDNotFound describes a response with status code 404, with default header values.

The component could not be found
*/
type GetComponentByUUIDNotFound struct {
}

func (o *GetComponentByUUIDNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/component/{uuid}][%d] getComponentByUuidNotFound ", 404)
}

func (o *GetComponentByUUIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
