// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openclarity/kubeclarity/api/client/models"
)

// PostApplicationsContentAnalysisIDReader is a Reader for the PostApplicationsContentAnalysisID structure.
type PostApplicationsContentAnalysisIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostApplicationsContentAnalysisIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostApplicationsContentAnalysisIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPostApplicationsContentAnalysisIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPostApplicationsContentAnalysisIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostApplicationsContentAnalysisIDCreated creates a PostApplicationsContentAnalysisIDCreated with default headers values
func NewPostApplicationsContentAnalysisIDCreated() *PostApplicationsContentAnalysisIDCreated {
	return &PostApplicationsContentAnalysisIDCreated{}
}

/*
PostApplicationsContentAnalysisIDCreated describes a response with status code 201, with default header values.

Application content analysis successfully reported.
*/
type PostApplicationsContentAnalysisIDCreated struct {
}

// IsSuccess returns true when this post applications content analysis Id created response has a 2xx status code
func (o *PostApplicationsContentAnalysisIDCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post applications content analysis Id created response has a 3xx status code
func (o *PostApplicationsContentAnalysisIDCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post applications content analysis Id created response has a 4xx status code
func (o *PostApplicationsContentAnalysisIDCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post applications content analysis Id created response has a 5xx status code
func (o *PostApplicationsContentAnalysisIDCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post applications content analysis Id created response a status code equal to that given
func (o *PostApplicationsContentAnalysisIDCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post applications content analysis Id created response
func (o *PostApplicationsContentAnalysisIDCreated) Code() int {
	return 201
}

func (o *PostApplicationsContentAnalysisIDCreated) Error() string {
	return fmt.Sprintf("[POST /applications/contentAnalysis/{id}][%d] postApplicationsContentAnalysisIdCreated ", 201)
}

func (o *PostApplicationsContentAnalysisIDCreated) String() string {
	return fmt.Sprintf("[POST /applications/contentAnalysis/{id}][%d] postApplicationsContentAnalysisIdCreated ", 201)
}

func (o *PostApplicationsContentAnalysisIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostApplicationsContentAnalysisIDNotFound creates a PostApplicationsContentAnalysisIDNotFound with default headers values
func NewPostApplicationsContentAnalysisIDNotFound() *PostApplicationsContentAnalysisIDNotFound {
	return &PostApplicationsContentAnalysisIDNotFound{}
}

/*
PostApplicationsContentAnalysisIDNotFound describes a response with status code 404, with default header values.

Application not found.
*/
type PostApplicationsContentAnalysisIDNotFound struct {
}

// IsSuccess returns true when this post applications content analysis Id not found response has a 2xx status code
func (o *PostApplicationsContentAnalysisIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post applications content analysis Id not found response has a 3xx status code
func (o *PostApplicationsContentAnalysisIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post applications content analysis Id not found response has a 4xx status code
func (o *PostApplicationsContentAnalysisIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post applications content analysis Id not found response has a 5xx status code
func (o *PostApplicationsContentAnalysisIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post applications content analysis Id not found response a status code equal to that given
func (o *PostApplicationsContentAnalysisIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post applications content analysis Id not found response
func (o *PostApplicationsContentAnalysisIDNotFound) Code() int {
	return 404
}

func (o *PostApplicationsContentAnalysisIDNotFound) Error() string {
	return fmt.Sprintf("[POST /applications/contentAnalysis/{id}][%d] postApplicationsContentAnalysisIdNotFound ", 404)
}

func (o *PostApplicationsContentAnalysisIDNotFound) String() string {
	return fmt.Sprintf("[POST /applications/contentAnalysis/{id}][%d] postApplicationsContentAnalysisIdNotFound ", 404)
}

func (o *PostApplicationsContentAnalysisIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostApplicationsContentAnalysisIDDefault creates a PostApplicationsContentAnalysisIDDefault with default headers values
func NewPostApplicationsContentAnalysisIDDefault(code int) *PostApplicationsContentAnalysisIDDefault {
	return &PostApplicationsContentAnalysisIDDefault{
		_statusCode: code,
	}
}

/*
PostApplicationsContentAnalysisIDDefault describes a response with status code -1, with default header values.

unknown error
*/
type PostApplicationsContentAnalysisIDDefault struct {
	_statusCode int

	Payload *models.APIResponse
}

// IsSuccess returns true when this post applications content analysis ID default response has a 2xx status code
func (o *PostApplicationsContentAnalysisIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this post applications content analysis ID default response has a 3xx status code
func (o *PostApplicationsContentAnalysisIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this post applications content analysis ID default response has a 4xx status code
func (o *PostApplicationsContentAnalysisIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this post applications content analysis ID default response has a 5xx status code
func (o *PostApplicationsContentAnalysisIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this post applications content analysis ID default response a status code equal to that given
func (o *PostApplicationsContentAnalysisIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the post applications content analysis ID default response
func (o *PostApplicationsContentAnalysisIDDefault) Code() int {
	return o._statusCode
}

func (o *PostApplicationsContentAnalysisIDDefault) Error() string {
	return fmt.Sprintf("[POST /applications/contentAnalysis/{id}][%d] PostApplicationsContentAnalysisID default  %+v", o._statusCode, o.Payload)
}

func (o *PostApplicationsContentAnalysisIDDefault) String() string {
	return fmt.Sprintf("[POST /applications/contentAnalysis/{id}][%d] PostApplicationsContentAnalysisID default  %+v", o._statusCode, o.Payload)
}

func (o *PostApplicationsContentAnalysisIDDefault) GetPayload() *models.APIResponse {
	return o.Payload
}

func (o *PostApplicationsContentAnalysisIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
