// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openclarity/kubeclarity/api/client/models"
)

// PutRuntimeScheduleScanConfigReader is a Reader for the PutRuntimeScheduleScanConfig structure.
type PutRuntimeScheduleScanConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutRuntimeScheduleScanConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPutRuntimeScheduleScanConfigCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutRuntimeScheduleScanConfigBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPutRuntimeScheduleScanConfigDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutRuntimeScheduleScanConfigCreated creates a PutRuntimeScheduleScanConfigCreated with default headers values
func NewPutRuntimeScheduleScanConfigCreated() *PutRuntimeScheduleScanConfigCreated {
	return &PutRuntimeScheduleScanConfigCreated{}
}

/*
PutRuntimeScheduleScanConfigCreated describes a response with status code 201, with default header values.

Success
*/
type PutRuntimeScheduleScanConfigCreated struct {
	Payload interface{}
}

// IsSuccess returns true when this put runtime schedule scan config created response has a 2xx status code
func (o *PutRuntimeScheduleScanConfigCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put runtime schedule scan config created response has a 3xx status code
func (o *PutRuntimeScheduleScanConfigCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put runtime schedule scan config created response has a 4xx status code
func (o *PutRuntimeScheduleScanConfigCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this put runtime schedule scan config created response has a 5xx status code
func (o *PutRuntimeScheduleScanConfigCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this put runtime schedule scan config created response a status code equal to that given
func (o *PutRuntimeScheduleScanConfigCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the put runtime schedule scan config created response
func (o *PutRuntimeScheduleScanConfigCreated) Code() int {
	return 201
}

func (o *PutRuntimeScheduleScanConfigCreated) Error() string {
	return fmt.Sprintf("[PUT /runtime/scheduleScan/config][%d] putRuntimeScheduleScanConfigCreated  %+v", 201, o.Payload)
}

func (o *PutRuntimeScheduleScanConfigCreated) String() string {
	return fmt.Sprintf("[PUT /runtime/scheduleScan/config][%d] putRuntimeScheduleScanConfigCreated  %+v", 201, o.Payload)
}

func (o *PutRuntimeScheduleScanConfigCreated) GetPayload() interface{} {
	return o.Payload
}

func (o *PutRuntimeScheduleScanConfigCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutRuntimeScheduleScanConfigBadRequest creates a PutRuntimeScheduleScanConfigBadRequest with default headers values
func NewPutRuntimeScheduleScanConfigBadRequest() *PutRuntimeScheduleScanConfigBadRequest {
	return &PutRuntimeScheduleScanConfigBadRequest{}
}

/*
PutRuntimeScheduleScanConfigBadRequest describes a response with status code 400, with default header values.

Failed to set scheduled scan config
*/
type PutRuntimeScheduleScanConfigBadRequest struct {
	Payload string
}

// IsSuccess returns true when this put runtime schedule scan config bad request response has a 2xx status code
func (o *PutRuntimeScheduleScanConfigBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put runtime schedule scan config bad request response has a 3xx status code
func (o *PutRuntimeScheduleScanConfigBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put runtime schedule scan config bad request response has a 4xx status code
func (o *PutRuntimeScheduleScanConfigBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put runtime schedule scan config bad request response has a 5xx status code
func (o *PutRuntimeScheduleScanConfigBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put runtime schedule scan config bad request response a status code equal to that given
func (o *PutRuntimeScheduleScanConfigBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put runtime schedule scan config bad request response
func (o *PutRuntimeScheduleScanConfigBadRequest) Code() int {
	return 400
}

func (o *PutRuntimeScheduleScanConfigBadRequest) Error() string {
	return fmt.Sprintf("[PUT /runtime/scheduleScan/config][%d] putRuntimeScheduleScanConfigBadRequest  %+v", 400, o.Payload)
}

func (o *PutRuntimeScheduleScanConfigBadRequest) String() string {
	return fmt.Sprintf("[PUT /runtime/scheduleScan/config][%d] putRuntimeScheduleScanConfigBadRequest  %+v", 400, o.Payload)
}

func (o *PutRuntimeScheduleScanConfigBadRequest) GetPayload() string {
	return o.Payload
}

func (o *PutRuntimeScheduleScanConfigBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutRuntimeScheduleScanConfigDefault creates a PutRuntimeScheduleScanConfigDefault with default headers values
func NewPutRuntimeScheduleScanConfigDefault(code int) *PutRuntimeScheduleScanConfigDefault {
	return &PutRuntimeScheduleScanConfigDefault{
		_statusCode: code,
	}
}

/*
PutRuntimeScheduleScanConfigDefault describes a response with status code -1, with default header values.

unknown error
*/
type PutRuntimeScheduleScanConfigDefault struct {
	_statusCode int

	Payload *models.APIResponse
}

// IsSuccess returns true when this put runtime schedule scan config default response has a 2xx status code
func (o *PutRuntimeScheduleScanConfigDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this put runtime schedule scan config default response has a 3xx status code
func (o *PutRuntimeScheduleScanConfigDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this put runtime schedule scan config default response has a 4xx status code
func (o *PutRuntimeScheduleScanConfigDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this put runtime schedule scan config default response has a 5xx status code
func (o *PutRuntimeScheduleScanConfigDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this put runtime schedule scan config default response a status code equal to that given
func (o *PutRuntimeScheduleScanConfigDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the put runtime schedule scan config default response
func (o *PutRuntimeScheduleScanConfigDefault) Code() int {
	return o._statusCode
}

func (o *PutRuntimeScheduleScanConfigDefault) Error() string {
	return fmt.Sprintf("[PUT /runtime/scheduleScan/config][%d] PutRuntimeScheduleScanConfig default  %+v", o._statusCode, o.Payload)
}

func (o *PutRuntimeScheduleScanConfigDefault) String() string {
	return fmt.Sprintf("[PUT /runtime/scheduleScan/config][%d] PutRuntimeScheduleScanConfig default  %+v", o._statusCode, o.Payload)
}

func (o *PutRuntimeScheduleScanConfigDefault) GetPayload() *models.APIResponse {
	return o.Payload
}

func (o *PutRuntimeScheduleScanConfigDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
