// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.1-0.20240823215434-d232e9efa9f5 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	. "github.com/openclarity/openclarity/uibackend/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get a list of findings impact for the dashboard.
	// (GET /dashboard/findingsImpact)
	GetDashboardFindingsImpact(ctx echo.Context) error
	// Get a list of finding trends for all finding types.
	// (GET /dashboard/findingsTrends)
	GetDashboardFindingsTrends(ctx echo.Context, params GetDashboardFindingsTrendsParams) error
	// Get a list of riskiest assets for the dashboard.
	// (GET /dashboard/riskiestAssets)
	GetDashboardRiskiestAssets(ctx echo.Context) error
	// Get a list of riskiest regions for the dashboard.
	// (GET /dashboard/riskiestRegions)
	GetDashboardRiskiestRegions(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetDashboardFindingsImpact converts echo context to params.
func (w *ServerInterfaceWrapper) GetDashboardFindingsImpact(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDashboardFindingsImpact(ctx)
	return err
}

// GetDashboardFindingsTrends converts echo context to params.
func (w *ServerInterfaceWrapper) GetDashboardFindingsTrends(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardFindingsTrendsParams
	// ------------- Required query parameter "startTime" -------------

	err = runtime.BindQueryParameter("form", true, true, "startTime", ctx.QueryParams(), &params.StartTime)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter startTime: %s", err))
	}

	// ------------- Required query parameter "endTime" -------------

	err = runtime.BindQueryParameter("form", true, true, "endTime", ctx.QueryParams(), &params.EndTime)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter endTime: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDashboardFindingsTrends(ctx, params)
	return err
}

// GetDashboardRiskiestAssets converts echo context to params.
func (w *ServerInterfaceWrapper) GetDashboardRiskiestAssets(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDashboardRiskiestAssets(ctx)
	return err
}

// GetDashboardRiskiestRegions converts echo context to params.
func (w *ServerInterfaceWrapper) GetDashboardRiskiestRegions(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDashboardRiskiestRegions(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/dashboard/findingsImpact", wrapper.GetDashboardFindingsImpact)
	router.GET(baseURL+"/dashboard/findingsTrends", wrapper.GetDashboardFindingsTrends)
	router.GET(baseURL+"/dashboard/riskiestAssets", wrapper.GetDashboardRiskiestAssets)
	router.GET(baseURL+"/dashboard/riskiestRegions", wrapper.GetDashboardRiskiestRegions)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RaUXPiOBL+KyrdPdxV+ZLsXt0LbwwhGddAoIDM3NbWPgi7jbWxJY8kJ+Gm+O9Xkmxs",
	"bBnMLMy8gdXd+rpbanW39A0HPM04A6YkHnzDGREkBQXC/AMWrmgK+idleIC/5iC22MOM6I/7YQ8L+JpT",
	"ASEeKJGDh2UQQ0o0X8RFShQe4JAo+Jey5GqbaX6pBGUbvNt5GN5JmiXwQBMFonM+S4Tr8tuipCJCHYNd",
	"Efxl4DstQWacSTAGe2YvjL+xsRDcaBFwpoAp/ZNkWUIDoihnt39KzvS3ara/C4jwAP/ttnLHrR2Vt8OM",
	"LopJ7JQhyEDQTIvCg3JOBGZSYwHLqOXWeQffGpxDhvj6TwgUUjFRiEokQOWCQYgoQyRJUEAkSMQjFBGa",
	"5ALkDfZwJngGQlGrcgpSko2RLoCEM5ZsS2O2fVN8sbPinYeHUoLyWcTN4jsQnHBrLYeXS1c6BuyHEwbV",
	"k640YTemVSEHWJ7iwe94+GWJxqNfkc+kIizQi2H4v1xA/cPjaF7/e8+DFxD1L+N3BYKRpP5txJkilIGo",
	"/0Z+qm36h9dWcPyeJZyqtr2CV/DvnTY58Po5xpQ8FwHcf3BbmqrEzZaLxCCiClLpnjFPErLW7AcrhQhB",
	"tm6nFGo/UBZStvHTjAQOG5AogkBBaFwoRzy3e69jYVKmYAMCm/izt+qxlVMa3wmxwLYSwML2ZltAJkBq",
	"aUjFgBRXJEEsT9cgzAazzBIRhQiSGQQ0ogEq4k7D06VebT1UEfd6ht2jOsi2EhMqlUZ7VIMMhMGNZMIV",
	"irgw5HuVCjq9wdrRpDZ4yhcPNVKtyh7yftn14TbOMmHcuUSOrMiHQ6hloJgPR5+Gj2Ps4c/Pk6fxYvjB",
	"n/ir37CHp8PJl+FCjyzHo8V4pT/5y9Hs6cF/fF4MV/7sCXt4MZutPvl6cPzf+WTmr5xRoJi8WuKHfrK+",
	"MetEuwZIEJd2R0ZW0+7F+pfuVZWS5I0I6BikMuAsoptcmHjdIUNwrl46Z5AQCOgafM0TBoKsaUJLvE2i",
	"Iw6SXcGirvOh+VY8Q/9BxXi1sCUXCkK03iJqREKIiAk01tLY67f0nKHs5BI88IILbjF8cbhTK/d8uK51",
	"4QTeILy8Bo0JzlYlI8EL2UCnBsX4xYHPrdyz8db3mgtvMX5xvAsr92y8td3vgmuHL452acSeDdYRjVyg",
	"62Tbi2P/XJd+pgrHYuWpg39/iBg6c7jrOqF+tpga4ewzWPYx/bSKgI0ixA48dSWyxXiftGJaIzVbX8Vt",
	"c8yJiss8KKIJ2AIqsOm7LEMxdhzcIk+6YLr84gy+l0t7a0dKD5schVjatqVxM/o6KheiYMPFtm3npU0a",
	"QbYPCbt90J7XO1n3NIrfMKT6p8mTmIJ3hWQexIjY/DzjunCnJCkmcsmnjjR/FEPwgnTOC1Ih/95DNEJF",
	"7b9OAP0DbjY3aLJlVKIVSKUpRv4SFcXiB2BBnBLxggItKOOU6XUVgodABf90oajXyY1NW4ygN6piyoxe",
	"JtigtxgEmP8tu74RiQQEXIQQFmj1CpdbqSBFejs4UdTaAA0XxlwoRFnEEVnzXDlnde4USCGkHarNuZRU",
	"2zOi7/sSo49UGRDGQHRGCgmvIKjanptTLEs+9x45moFccD879to5WvRDv6zZqCx7mjQf6Sbe07VFTCGk",
	"eXqEYMLf9qOuAqhIjdq262xmZLlInAOvIKS7NeIyhjMnu5wHs0qvHpmhG+ICNtUacyYoujrcpyTmEEfC",
	"MHUV5JUKPQ70gtjsYS30jPNuQeULBams3c6v2UTBXyZVVbpVcp6Z0VL5sjVgLlChdYMra7drYutbjh1B",
	"2RRxTbwna5hOmCXnNdGdqFi6wRWM18TWs0DpxtgU8D01yTmQjwUCG8sckUBUA+5SpSAwyU+RqBcBzyTr",
	"Os+JeM5CxE1mlN6gRZ2D8YrhjSYJYlyhNSABmTFU7yqnEY2/2xqFNTuiuaMPa+I6s+5txXVSv3g5eVli",
	"CHded+fZCdruQ0e1VuWK7azPMnXmZ8V4n0puUSM9BvBaR7mo9O8B8yjEZpN5Op7OFr9hD38aL57GE+zh",
	"4Xw+8UdlE/nBX0xNr9mVOtm+h+NsZeGIJ3nK3F1YYOGEso4msC4R5s5SWXvyoFQuqmTTLoihCIiuVD2i",
	"bAMiE9TV4X7iCgZIxVQiKs3ezBn9mjtrbnPhe0w1Q9ClnMstrtbR5RaO3DvodPvKje/zYQRvAb16j+kQ",
	"wtZ1Wynl9yEZac6Td4j9K7kD4VUZd3iObrtz2A5DuJ1h0TsiohI0ON8O04LPVDGBso8O/mKB0zlJC/Wa",
	"SFgG/OBiyJ5DtSvV0rCddLa/0jV+EuG1NuFrc/32dkwP0Oec5x2N5Guc7oIqGpCkET1G3dfNMd3E/akT",
	"/tafODUdgv70DDYJ3dB1An15TnrJ1ecYLfyVPxrqI/ej//gRe3g6vvefp9jDk9kX7OGn8ePEf/Q/TFyH",
	"r56TFm4p3k/gWQZslBA9EXr20XDu64x7v2fxLzd3N3caG8+AkYziAf73zd3NL9g2p42/b0Mi4zUnIryN",
	"WreeG7vK9PowZZsf4gF+BHVf8jQuShtvmn69u7vYU6bGTI7XTMs8CMAG+BAikied5+Ae5O3BqyvzACpP",
	"UyK2Vk1EUHJ4eyHL5nHZONxb78awO6xZ3Yv0tmbB4h28qfvdrUtFclu9Ttt5J4nLF3i7P36A08p7mp/j",
	"tBNXTg2/iVYf6aTfGq2nKxq0MdOPNmiz8D+9C0S7GO9tzpLnB9iznOqnGbRsOTgtutv9PwAA///ZdWWx",
	"bSsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
