// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDashboardMostVulnerableHandlerFunc turns a function with the right signature into a get dashboard most vulnerable handler
type GetDashboardMostVulnerableHandlerFunc func(GetDashboardMostVulnerableParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDashboardMostVulnerableHandlerFunc) Handle(params GetDashboardMostVulnerableParams) middleware.Responder {
	return fn(params)
}

// GetDashboardMostVulnerableHandler interface for that can handle valid get dashboard most vulnerable params
type GetDashboardMostVulnerableHandler interface {
	Handle(GetDashboardMostVulnerableParams) middleware.Responder
}

// NewGetDashboardMostVulnerable creates a new http.Handler for the get dashboard most vulnerable operation
func NewGetDashboardMostVulnerable(ctx *middleware.Context, handler GetDashboardMostVulnerableHandler) *GetDashboardMostVulnerable {
	return &GetDashboardMostVulnerable{Context: ctx, Handler: handler}
}

/* GetDashboardMostVulnerable swagger:route GET /dashboard/mostVulnerable getDashboardMostVulnerable

Get top 5 most vulnerable applications, resources and packages

*/
type GetDashboardMostVulnerable struct {
	Context *middleware.Context
	Handler GetDashboardMostVulnerableHandler
}

func (o *GetDashboardMostVulnerable) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDashboardMostVulnerableParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
